[package]
name = "ir_file"
version = "0.1.0"
edition = "2018"

[dependencies]
codegen = "0.1.3"
lexpr = "0.2.6"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
name = "real_world"
harness = false
