##
## We use a Makefile to ensure that we generate the runtime before we build
## `jssat`. We must generate the runtime so that we can include it in the
## compiler, so that the user's linker can be invoked to link the runtime and
## generated object file to produce a binary.
##

[config]
# https://github.com/sagiegurari/cargo-make/issues/56#issuecomment-359041088
skip_core_tasks = true
# https://github.com/sagiegurari/cargo-make/issues/448#issuecomment-674697159
# https://github.com/sagiegurari/cargo-make#disabling-workspace-support
default_to_workspace = false

[tasks.dev]
script_runner = "@shell"
script = '''
cargo build -p jssatrt
cargo run -p jssat
'''

[tasks.release]
script_runner = "@shell"
script = '''
cargo build -p jssatrt --release
cargo build -p jssat --release
'''
