[package]
name = "jssatrt"
version = "0.1.0"
authors = ["SirJosh3917 <SirJosh3917@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "jssatrt"
crate-type = ["staticlib", "cdylib"]

[dependencies]
mimalloc = "0.1.26"
widestring = "0.4.3"
