[package]
name = "jssatrt"
version = "0.1.0"
authors = ["SirJosh3917 <SirJosh3917@users.noreply.github.com>"]
edition = "2021"

[lib]
name = "jssatrt"
crate-type = ["staticlib", "cdylib"]

[dependencies]
mimalloc = "0.1.27"
widestring = "0.5.1"
